export const constValues = {
  welcome: 'Welcome',
  loginPageDescription: 'Home assignment for Automation Developer position.',

  langEnglish: 'English',
  userName: 'Admin',
  primaryTitle: 'Welcome, Candidate!',
  primaryDescription: 'Happy coding and good luck, may the Force be with you!',

  logoSrc: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Unity_2021.svg',
  happyFolderLabel: 'Happy Folder',
  publisherLabel: 'Publisher',
  profileLabel: 'Profile',
  postLabel: 'Post',
  pagesTitleLabel: 'Pages',
  dashboardLabel: 'Dashboard',
  desighSystemsLabels: 'Design System Examples',
  publisherPath: 'Home / Publisher ',
  newPublisherPath: 'Home / Publisher / Create new',
  createNewTitle: 'Create new',
  publisherNameLabel: 'Name',
  publisherEmailLabel: 'Email',
  save: 'Save',
  firstPublisherName: 'first publisher',
  firstPublisherEmail: 'firstPub@mail.com',
  secondPublisherName: 'second publisher',
  secondPublisherEmail: 'secondPub@mail.com',
  deleteAction: 'Delete',
  noRecordsLabel: 'No records',
  noRecordsDescription: 'There are no records in this resource',
  thirdPublisherName: 'third publisher',
  thirdPublisherEmail: 'thirdPub@mail.com',
  postPath: 'Home / Post ',
  postTitle: 'first post title',
  postContent: 'first post content',
  activePostStatus: 'ACTIVE',
  removedPostStatus: 'REMOVED',
  JsonDataNumber: '5',
  JsonDataText: 'five',
  profilePath: 'Home / Profile ',
  firstBioProfile: 'First profile bio',
  secondBioProfile: 'Second profile bio',
  jsonData: {
    number: '5',
    text: 'five',
  },
};
