export const postSelectors = {
  createButton: 'a[data-testid="action-new"]',
  editTitleArea: 'section[data-css="Post-edit-title"]',
  title: '#title',
  editContentArea: 'section[data-css="Post-edit-content"]',
  content: '#content',
  editJson: 'section[data-testid="property-edit-someJson"]',
  addJsonButton: 'button[data-testid="someJson-add"]',
  jsonForm: 'section[data-rfd-droppable-id="someJson"]',
  editStatus: 'section[data-css="Post-edit-status"]',
  dropDown: 'div[class="adminjs_Select css-b62m3t-container"]',
  editPublished: 'section[data-css="Post-edit-published"]',
  publishedCheckBox: 'span[class="sc-gLDzan fGtBdP  adminjs_Checkbox"]',
  editPublisher: 'section[data-css="Post-edit-publisher"]',
  adminBox: 'section[class="sc-dmqHEX kTAUKl adminjs_Box"]',
  jsonDatePicker: 'input[class="react-datepicker-ignore-onclickoutside"]',
  datePickerPopup: 'div[class="react-datepicker"]',
  optionMenu: 'div[class=" css-12r18xa-MenuList"]',
  option: 'div[class=" css-jvatm4-option"]',
  saveButton: 'button[data-testid="button-save"]',
  postTitle: 'h2[class="sc-ilEZps eOGlIj sc-hhGHuG dgJiMC adminjs_Header adminjs_H2"]',
  pagePath: 'section[class="sc-dmqHEX dWJNXt adminjs_Box"]',
  mainSection: 'section[class="sc-dmqHEX sc-ldFCYb bMCSKi fGSGQw adminjs_InfoBox"]',
  postTable: 'table[data-css="Post-table"]',
  postTableBody: 'tbody[data-css="Post-table-body"]',
  tableTitle: 'td[data-property-name="title"]',
  tableContent: 'td[data-property-name="content"]',
  tableStatus: 'td[data-property-name="status"]',
  actionButton: 'div[class="sc-cPlDXj crxVEM adminjs_ButtonGroupItem"]',
  dropDownMenu: 'section[class="sc-dmqHEX sc-BKAtq eaBOiP bixteG adminjs_Box adminjs_DropDown-Stick-right adminjs_DropDownMenu adminjs_Box"]',
  editOption: 'a[data-testid="action-edit"]',
  deleteOption: 'a[data-testid="action-delete"]',
  popup: 'section[class="sc-dmqHEX sc-gHyekI laEziR bHoukU adminjs_Box"]',
  confirmButton: 'button[label="Confirm"]',
};
