export const profileSelectors = {
  editProfileName: 'section[data-css="Profile-edit-bio"]',
  editProfilePublisher: 'section[data-css="Profile-edit-publisher"]',
  saveButton: 'button[data-testid="button-save"]',
  bio: '#bio',
  createButton: 'a[data-testid="action-new"]',
  publisherBox: 'div[class="adminjs_Select css-b62m3t-container"]',
  option: 'div[class=" css-jvatm4-option"]',
  mainSection: 'section[class="sc-dmqHEX jNOOKd adminjs_Box"]',
  pagePath: 'section[class="sc-dmqHEX dWJNXt adminjs_Box"]',
  profileTable: 'table[data-css="Profile-table"]',
  profileBody: 'tbody[data-css="Profile-table-body"]',
  profileId: 'td[data-property-name="id"]',
  profileBio: 'td[data-property-name="bio"]',
  profilePubEmail: 'td[data-property-name="publisher"]',
  actionButton: 'a[data-testid="actions-dropdown"]',
  dropDownMenu: 'section[class="sc-dmqHEX sc-BKAtq eaBOiP bixteG adminjs_Box adminjs_DropDown-Stick-right adminjs_DropDownMenu adminjs_Box"]',
  filterIdField: 'input[name="filter-id"]',
  filterButton: 'a[data-css="Profile-filter-button"]',
  filterFooter: 'section[data-css="Profile-filter-drawer-footer"]',
  applyChangesButton: 'button[data-css="Profile-filter-drawer-button-apply"]',
  optionsMenu: 'div[class=" css-12r18xa-MenuList"]',
  deleteAction: 'a[data-testid="action-delete"]',
  popup: 'section[class="sc-dmqHEX sc-gHyekI laEziR bHoukU adminjs_Box"]',
  confirmButton: 'button[label="Confirm"]',
};
