export const publisherSelectors = {
  createPublisherButton: 'a[data-testid="action-new"]',
  editNameArea: 'section[data-testid="property-edit-name"]',
  name: '#name',
  editEmailArea: 'section[data-testid="property-edit-email"]',
  email: '#email',
  saveButton: 'button[data-testid="button-save"]',
  title: 'h2[class="sc-ilEZps eOGlIj sc-hhGHuG dgJiMC adminjs_Header adminjs_H2"]',
  pagePath: 'section[class="sc-dmqHEX dWJNXt adminjs_Box"]',
  mainSection: 'section[class="sc-dmqHEX sc-ldFCYb bMCSKi fGSGQw adminjs_InfoBox"]',
  publishersTable: 'section[data-css="Publisher-list-table-wrapper"]',
  tableName: 'td[data-property-name="name"]',
  tableEmail: 'td[data-property-name="email"]',
  tableId: 'td[data-property-name="id"]',
  actionButton: 'div[class="sc-cPlDXj crxVEM adminjs_ButtonGroupItem"]',
  dropDownMenu: 'section[class="sc-dmqHEX sc-BKAtq eaBOiP bixteG adminjs_Box adminjs_DropDown-Stick-right adminjs_DropDownMenu adminjs_Box"]',
  deleteAction: 'a[data-testid="action-delete"]',
  popup: 'section[class="sc-dmqHEX sc-gHyekI laEziR bHoukU adminjs_Box"]',
  confirmButton: 'button[label="Confirm"]',
  filterButton: 'a[data-css="Publisher-filter-button"]',
  applyChangesButton: 'button[data-css="Publisher-filter-drawer-button-apply"]',
  publisherResultTitle: 'h4[class="sc-ilEZps kOqYuz sc-gXSCqU adminjs_Header adminjs_H4"]',
  publisherResultDescription: 'div[class="sc-gjTGSA cMvPaq adminjs_Text"]',
  filterIdField: 'input[name="filter-id"]',
};
